package enums;

public enum ViewType {

  COFFEE_MENU_VIEW,
  CREATE_ACCOUNT_VIEW,
  CREATE_COFFEE_VIEW,
  CREATE_ORDER_VIEW,
  LOGIN_VIEW,
  ORDER_SUMMARY_VIEW,
  UPDATE_ACCOUNT_VIEW,
  UPDATE_COFFEE_VIEW,
  ORDER_HISTORY_VIEW,
}
