package enums;

public enum ViewType {

    COFFEE_MENU_VIEW,
    CREATE_ACCOUNT_VIEW,
    CREATE_COFFEE_VIEW,
    CREATE_ORDER_VIEW,
    ORDER_HISTORY_VIEW,
    LOGIN_VIEW,
    ORDER_DETAIL_VIEW,
    UPDATE_ACCOUNT_VIEW,
    UPDATE_COFFEE_VIEW,
    CUSTOMER_DETAIL_VIEW,
    VIEW_ALL_CUSTOMERS_VIEW,
    VIEW_ALL_ORDERS_VIEW,
}
